---
resources:
  - name: resource-concourse-features
    type: git
    source:
      uri: https://github.com/dammc/concourse-hello-world.git
      branch: features

  - name: resource-app-features
    type: git
    source:
      uri: https://github.com/dammc/hello-world-app.git
      branch: features

jobs:
  - name: job-hello-world
    public: true
    plan:
    - get: resource-concourse-features
    - get: resource-app-features
      trigger: true
    - task: unit-test
      file: resource-concourse-features/Tasks/task_unit_test.yml

groups:
  - name: demo
    jobs:
      - job-hello-world
      
