---
resources:
  - name: resource-master
    type: git
    source:
      uri: https://github.com/dammc/concourse-hello-world.git
      branch: master

resources:
  - name: resource-features
    type: git
    source:
      uri: https://github.com/dammc/concourse-hello-world.git
      branch: features

jobs:
  - name: job-hello-world
    public: true
    plan:
    - get: resource-features
    - task: hello-world
      file: Tasks/task_hello_world.yml

groups:
  - name: demo-app
    jobs:
      - build-demo-app
      - deploy-demo-app
