---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine}

inputs:
  - name: resource-app-features
  - name: resource-concourse-master
  

run:
  path: resource-concourse-master/Tasks/unit_test.sh
  
