---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs: 
  - name: resource-master

run:
  path: resource-master/Tasks/task-hello-world/task_hello_world.yml
  
