---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine}

inputs: 
  - name: resource-master

run:
  path: resource-master/Tasks/task-hello-world/hello_world_app.sh
  
